# Basics

In [173]:
import numpy as np

In [174]:
a = np.array([1,2,3])

In [175]:
print(a)

[1 2 3]


In [176]:
b = np.array([[9.1, 5.2], [3.3, 5.9]])

In [177]:
print(b)

[[9.1 5.2]
 [3.3 5.9]]


In [178]:
d = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])

In [179]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Getting Dimensions of Numpy Arrays

In [180]:
a.ndim

1

In [181]:
b.ndim

2

## Shape

In [182]:
a.shape

(3,)

In [183]:
b.shape

(2, 2)

## Type

In [184]:
a.dtype

dtype('int32')

In [185]:
a = np.array([1,2,3], dtype = 'int16')

In [186]:
a.dtype

dtype('int16')

## Size

In [187]:
a.itemsize

2

In [188]:
a.size

3

In [189]:
a.nbytes

6

In [190]:
b.itemsize

8

## Accessing/Chasing specific elements, rows, columns etc

In [191]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [192]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [193]:
a[1, 5]

13

In [194]:
a[1, -2]

13

In [195]:
a[0, ...]

array([1, 2, 3, 4, 5, 6, 7])

In [196]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [197]:
a[:, 0]

array([1, 8])

In [198]:
a[1,5] = 20

In [199]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [200]:
a[:, 2] = 5

In [201]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [202]:
a[:, 2] = [1,2]

In [203]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [204]:
# Tip! To get a specific element, "work outside in"

In [205]:
d[:,1,:] = [[9,9],[8,8]]

In [206]:
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [207]:
e = np.random.randint(1,9,size=(3,3))
print(e)

[[1 2 8]
 [5 4 1]
 [2 4 1]]


In [208]:
print(e[[1,2],[0,2]])
print("Advanced indexing")
print(e[1:3, [0,2]])

[5 1]
Advanced indexing
[[5 1]
 [2 1]]


In [209]:
# Remenber! replacing works till the replaced array is of the same dimension

# Initializing different types of Arrays

In [210]:
a = np.zeros(5)

In [211]:
print(a)

[0. 0. 0. 0. 0.]


In [212]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [213]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [214]:
np.arange(2,9,3)

array([2, 5, 8])

In [215]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [216]:
np.full_like(d,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [217]:
x = [1,2,3]
c = np.asarray(x)

In [218]:
print(c)

[1 2 3]


In [219]:
c[2] = 5

In [220]:
print(c)

[1 2 5]


In [221]:
print(x)

[1, 2, 3]


In [222]:
x = (7,8,9)
c = np.asarray(x)

In [223]:
print(c)

[7 8 9]


In [224]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 

In [225]:
type(a[0])

tuple

In [226]:
a.dtype

dtype('O')

In [227]:
s = list('Hello World')
a = np.asarray(s)

In [228]:
print(s)

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


Random numbers

In [229]:
c = np.random.rand(2,2)

In [230]:
print(c)

[[0.526325   0.55547927]
 [0.85102811 0.85238012]]


In [231]:
min = 0.75
max = 1.5
A = ( np.random.rand(2,3) * (max - min) ) + min

In [232]:
print(A)

[[1.308418   1.43341665 0.96972901]
 [1.32069767 0.80651708 0.83583507]]


In [233]:
np.random.randint(3,10,size=(2,2))

array([[8, 5],
       [4, 4]])

# Repeating an array

In [234]:
arr = np.array([[1,2,3]])

In [235]:
r1 = np.repeat(arr,4,axis=0)
r2 = np.repeat(arr,4,axis=1)

In [236]:
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


# Copying arrays

In [237]:
a = np.array([1,2,3])

In [238]:
b = a
b[0] = 100

In [239]:
print(b)
print(a)

[100   2   3]
[100   2   3]


In [240]:
a = np.array([1,2,3])

In [241]:
b = a.copy()
b[0] = 100

In [242]:
print(b)
print(a)

[100   2   3]
[1 2 3]


# Broadcasting

In [243]:
print(a)
print(a+2)

[1 2 3]
[3 4 5]


In [244]:
# This element wise operation holds true for every operator in python

In [245]:
print(a)
print(b)
print(a*b)

[1 2 3]
[100   2   3]
[100   4   9]


# Mathematics

In [246]:
print(np.log(np.array([1,2,3])))

[0.         0.69314718 1.09861229]


In [247]:
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [248]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


# Linear Algebra

In [249]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [250]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [251]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [252]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [253]:
np.linalg.det(np.identity(3))

1.0

# Statistics

In [254]:
a = np.array([[1,2,3],[4,5,6]])

In [255]:
np.min(a)

1

In [256]:
np.max(a, axis = 1)

array([3, 6])

In [257]:
np.sum(a)

21

In [258]:
np.sum(a, axis=0)

array([5, 7, 9])

In [259]:
np.mean(a)

3.5

In [260]:
np.median(a)

3.5

In [261]:
np.average(a)

3.5

In [262]:
print(np.std(a))
print(np.std(a) ** 2)

1.707825127659933
2.9166666666666665


In [263]:
np.var(a)

2.9166666666666665

# Reorganizing Arrays

In [264]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [265]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [266]:
# Remember! As long as it has same amount of values, it's fair game

In [267]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [268]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])